### PR TITLE
Fix for ACE generation errors.

### PR DESCRIPTION
**Pull request by AlexKuhnle**
List of dictionaries can't be joined, instead first extract the corresponding string argument.

### CODE REVIEW

**Comment by goodmami** [comment]
Good catch. I know the kind of ACE errors that can reach that point in the code, but I'm unable to recreate it. Do you have a sentence that causes such a condition?

Also, pull requests should be applied to the `develop` branch, not `master` (see https://github.com/delph-in/pydelphin/blob/master/CONTRIBUTING.md#branching). I think I can manually do it, though.

**Comment by goodmami** [comment]
Ok, I merged it into develop, but the PR didn't close automatically so I'll close it now.

I'd still appreciate the sentence that causes the error so I can test it out. Thanks!

**Comment by AlexKuhnle** [comment]
I encountered this when I was experimenting with what resulted in an "invalid" MRS, essentially by underspecifying an ARG1 with an ARG link in e.g. **_"Kim likes Sandy."_** (see for _like_v_1):
`[ TOP: h0 RELS: < [ proper_q_rel<-1:-1> LBL: h1 ARG0: x6 [ x IND: + NUM: sg PERS: 3 ] RSTR: h9 ] [ named_rel<-1:-1> LBL: h2 ARG0: x6 CARG: "Kim" ] [ _like_v_1_rel<-1:-1> LBL: h3 ARG: x6 ARG0: e7 [ e TENSE: pres SF: prop MOOD: indicative PROG: - PERF: - ] ARG2: x8 [ x IND: + NUM: sg PERS: 3 ] ] [ named_rel<-1:-1> LBL: h4 ARG0: x8 CARG: "Sandy" ] [ proper_q_rel<-1:-1> LBL: h5 ARG0: x8 RSTR: h10 ] > HCONS: < h10 qeq h4 h9 qeq h2 > ]`

This gave the following list for `results` in the respective code line - the fact that an error is thrown is obviously  a good thing... :-)
`[{'SENT': "type inference:  no glb for 'g(3271)' and 'unknown_relation'"}, {'SENT': '  PRED\tappropriate to relation'}, {'SENT': '  LBL\tappropriate to relation'}, {'SENT': '  ARG0\tappropriate to arg0_relation'}, {'SENT': '  ARG2\tappropriate to arg2_relation'}, {'SENT': '  ARG\tappropriate to unknown_relation'}]`

**Comment by goodmami** [comment]
Thanks for following up. I was able to recreate the error with this sentence and the 1214 release of the ERG.

**Pull request closed without merging**
